name: zazukoians-hydra-fullstack
services:
  api:
    type: node
    port: 9000
    ssl: false
    command: cd api; npm start
    moreHttpPorts:
      - 9001
    overrides:
      ports:
        - '9001:9001'
      environment:
        - DEBUG=hydra-fullstack*,hydra-box*
        - BASE_IRI=http://hydra-fullstack.lndo.site/
        - SPARQL_QUERY_ENDPOINT=http://fuseki:3030/telco/query
        - SPARQL_UPDATE_ENDPOINT=http://fuseki:3030/telco/update
  ui:
    type: node
    port: 8080
    ssl: false
    command: cd ui; npm start
  fuseki:
    type: compose
    services:
      image: blankdots/jena-fuseki:fuseki3.13.1
      ports:
        - '3030'
      environment:
        - ADMIN_PASSWORD=password
        - ENABLE_DATA_WRITE=true
        - ENABLE_UPDATE=true
        - ENABLE_UPLOAD=true
      command: /docker-entrypoint.sh /jena-fuseki/start-fuseki.sh
      volumes:
        - ./fuseki/config.ttl:/data/fuseki/config/config.ttl
proxy:
  api:
    - hydra-fullstack.lndo.site:9000
  ui:
    - hydra-fullstack-ui.lndo.site:8080
  fuseki:
    - hydra-fullstack-db.lndo.site:3030
